CREATE USER "LIQUIBASE_USER" IDENTIFIED BY "Qwerty!23456";
GRANT CONNECT TO LIQUIBASE_USER with admin option;
ALTER USER "LIQUIBASE_USER" QUOTA UNLIMITED ON "DATA";
GRANT SUPER_USER to LIQUIBASE_USER;